### ISSUE TITLE
ske: Atlas module that automatically packs a list of arbitrary images.

### ISSUE THREAD

**Issue by marekmaskarinec** [tophat2d/tophat#118]
## Original issue:

[~mrms/tophat#42](https://todo.sr.ht/~mrms/tophat/42)

**Comment by marekmaskarinec** [comment]
@skejeton are you okay with `atlas.Atlas.pack`? If so, please close this.

**Comment by skejeton** [comment]
Is the cell size sparse or constant?

**Comment by marekmaskarinec** [comment]
It's constant, since tophat atlases don't allow variable cell sizes anyways.

**Comment by skejeton** [comment]
I think this works for games with blocks, although I was more thinking for atlases of texture regions, where the ordering doesn't matter. I think this is good enough for now though, if anything it could be an extension, and someone can make their own packer.
