### ISSUE TITLE
ske: Flipping doesn't work with ninepatch rects or cropping.

### ISSUE THREAD

**Issue by marekmaskarinec** [tophat2d/tophat#121]
## Original issue:

[~mrms/tophat#26](https://todo.sr.ht/~mrms/tophat/26)

### mrms

I think flipping works with cropping. ~ske, please test using `imaget.um`.

### mrms

I'd say the issue is with cropping, not nine-patch.

**Comment by marekmaskarinec** [comment]
@skejeton I think this issue should be fixed now. Could you please test it?

**Comment by marekmaskarinec** [comment]
https://github.com/marekmaskarinec/tophat/blob/d4b82a449a511baea885cb86bc593d1f592d2ebd/src/image.c#L289

**Comment by skejeton** [comment]
![image](https://github.com/marekmaskarinec/tophat/assets/27076041/1c23ac25-c4f9-4230-be01-7a8362eba628)
definitely not Ninepatch, this is what I get:
