### ISSUE TITLE
mrms: Input on linux isn't keyboard layout independant

### ISSUE THREAD

**Issue by marekmaskarinec** [tophat2d/tophat#123]
## Original issue:

[~mrms/tophat#11](https://todo.sr.ht/~mrms/tophat/11)

## Initial message:

Moved from https://todo.sr.ht/~mrms/tophat-sokol/3

### ske

dead link

**Comment by skejeton** [comment]
Does it still reproduce @marekmaskarinec

**Comment by marekmaskarinec** [comment]
Yes, it does. Perhaps we should take this up to sokol.

**Comment by marekmaskarinec** [comment]
@vtereshkov @skejeton could you please test this too, just so we know this isn't an issue with my setup?

**Comment by skejeton** [comment]
I use qwerty, but if I switch to the Russian layout everything works the same.

**Comment by skejeton** [comment]
> Is it possible that the russian layout is still technically qwerty? Could you please try something alternative like colemak or dvorak? If you also find this issue, I will report this upstream to sokol.

I will try it sometime this week. It technically should work on Windows as I know it uses scancodes instead of VK codes for a fact. I'll look into sokol linux impl as well.

**Comment by marekmaskarinec** [comment]
I will try making a PR to sokol to fix this. I know we've solved this in the past in tophat before sokol.

**Comment by marekmaskarinec** [comment]
This is how it used to be done: https://github.com/tophat2d/tophat/blob/edab44fd4f96eb90ae6bbd40f12ed6ff09cfd85e/src/window.c#L202

**Comment by vtereshkov** [comment]
On my WSL, everything works fine in both English and Russian layouts. Physically it's QWERTY, of course.

**Comment by skejeton** [comment]
Setting Dvorak on Windows has no effect on which key you press. So It's probably a Linux-only issue. Sending a PR to sokol would be cool.

**Comment by marekmaskarinec** [comment]
PR submitted: https://github.com/floooh/sokol/pull/1078

**Comment by skejeton** [comment]
verify again

**Comment by marekmaskarinec** [comment]
Verified
