### ISSUE TITLE
ske: `window.wp` is not always synced with the actual viewport

### ISSUE THREAD

**Issue by marekmaskarinec** [tophat2d/tophat#126]
## Original issue:

[~mrms/tophat#17](https://todo.sr.ht/~mrms/tophat/17)

## Initial message:

for example: setting the viewport when we end the render target

### mrms

This would require some deeper edits, since rn it would create an import cycle between `image.um` and `window.um`.

**Comment by marekmaskarinec** [comment]
This could be solved by moving render target related stuff to a separate file, maybe named `rt.um`.  This will have 2 benefits:

* we can properly set `window::wp` during render targets
* the user won't have to supply `wp` on their own when ending a render target
* `image.um`, which is currently a pretty big file will get simpler

This is just a temporary change before the new renderer, where it might be better to have some kind of render contexts or something for this.

What do you think @skejeton. If you agree, I can start the works.

**Comment by skejeton** [comment]
> This could be solved by moving render target related stuff to a separate file, maybe named `rt.um`.  This will have 2 benefits:
> 
> * we can properly set `window::wp` during render targets
> * the user won't have to supply `wp` on their own when ending a render target
> * `image.um`, which is currently a pretty big file will get simpler
> 
> This is just a temporary change before the new renderer, where it might be better to have some kind of render contexts or something for this.
> 
> What do you think @skejeton. If you agree, I can start the works.

I agree. During the development of the new renderer we'll need to think of how to make the viewports a bit more flexible as well (#3

**Comment by marekmaskarinec** [comment]
Implemented.
