### ISSUE TITLE
Add `rectIntersection` to rect.um/coll.um

### ISSUE THREAD

**Issue by skejeton** [tophat2d/tophat#194]
returns intersection rect between two rects.

```
fn rectIntersection*(a, b: rect::Rect): rect::Rect {
  x := max(a.x, b.x)
  y := max(a.y, b.y)
  return {x, y, min(a.x + a.w, b.x + b.w) - x, min(a.y + a.h, b.y + b.h) - y}
}
```
![image](https://github.com/tophat2d/tophat/assets/27076041/99cb5b2c-d656-418d-8b89-9643c1525e97)

**Comment by marekmaskarinec** [comment]
Make a PR

**Comment by skejeton** [comment]
I'm saving this for after we're done with the API update.
